version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - blackbox

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - $PWD/ambassador.yaml:/ambassador/ambassador-config/ambassador.yaml
    depends_on:
      - prometheus

  blackbox:
    image: prom/blackbox-exporter:master
    expose:
      - 9115
    volumes:
      - $PWD/blackbox.yml:/etc/blackbox_exporter/config.yml
