version: "3"

services:
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - prometheus_data:/prometheus
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - blackbox

  grafana:
    image: grafana/grafana
    ports:
      - 4545:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  blackbox:
    image: prom/blackbox-exporter:master
    expose:
      - 9115
    volumes:
      - $PWD/blackbox.yml:/etc/blackbox_exporter/config.yml

volumes: 
  prometheus_data: {}
  grafana_data: {}