scrape_configs:

- job_name: 'prometheus'
  scrape_interval: 15s
  static_configs:
      - targets: ['localhost:9090']

- job_name: blackbox
  scrape_interval: 1s
  metrics_path: /probe
  params:
    module: [icmp]
  static_configs:
    - targets:
      - 10.0.1.5
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
